"use strict";
// ---------------------------------------------------------------------------
// Every line of content below is loaded from data/*.json. Those files are
// copied byte for byte from the pipeline runs by tools/sync_datatables.py.
// Nothing in this file authors game content.
// ---------------------------------------------------------------------------
const DT = {};
let SINK = null;   // tests replace this; the browser leaves it null
function setSinks(s){ SINK = s; }
const $ = id => SINK ? SINK(id) : document.getElementById(id);

const S = {
  act: 1, hazard: 0, hzTurn: 0, hzFails: 0, totalFails: 0,
  limping: false, phaseIx: 0, over: false, mode: "boot",
  // act 3
  dog: [0,0], rex: [5,5], kid: [7,4], distMax: 11,
  stamina: 15, round: 0, charge: 100, moves: [], lastCat: null,
  priorAttempt: null, attempts: 0, checkpoint: null, spoken: [], log: [], log: []
};

const MAXROUNDS = 15, START_CHARGE = 100, PURSUIT = 8, HOLD = 1, SOLAR = 2;
const BAND_CLIN = 60, BAND_CONF = 30, WINDOW = 4, FREQ = 20;
const STEP = {left:[-1,0], right:[1,0], up:[0,-1], down:[0,1]};

const man = (a,b) => Math.abs(a[0]-b[0]) + Math.abs(a[1]-b[1]);
const eq = (a,b) => a[0]===b[0] && a[1]===b[1];

function say(html, cls){
  S.log.push(String(html).replace(/<[^>]*>/g, ""));   // visible to headless tests
  if(typeof document === "undefined"){ return; }
  const p = document.createElement("p");
  if(cls) p.className = cls;
  p.innerHTML = html;
  $("say").appendChild(p);
  while($("say").children.length > 4) $("say").removeChild($("say").firstChild);
}
function clearSay(){ if(typeof document === "undefined") return; $("say").innerHTML = ""; }

// ---------------------------------------------------------------------- boot
async function boot(){
  const names = ["DT_JourneyHazards","DT_ArenaPhases","DT_NemesisReads",
                 "DT_RetryReads","DT_JourneyBeats","MANIFEST"];
  for(const n of names){
    const r = await fetch("data/" + n + ".json");
    DT[n] = await r.json();
  }
  DT.hazards = DT.DT_JourneyHazards.slice().sort((a,b)=>a.Day-b.Day);
  DT.phases  = DT.DT_ArenaPhases.slice().sort((a,b)=>a.PhaseIndex-b.PhaseIndex);
  const rows = DT.MANIFEST.reduce((n,m)=>n+m.rows,0);
  $("prov").innerHTML = "All content generated by the Rex Machina agent pipelines. " +
    rows + " rows across " + DT.MANIFEST.length + " DataTables, loaded unmodified from <code>data/</code>.";
  startHazard(0);
}

// ------------------------------------------------------------- ACTS 1 and 2
// Six generated encounters. Each row carries a Telegraph, a WindowTurns count
// and an EscapeCondition: move on the turn after the tell, not before.
function telegraphTurn(h){ return Math.max(1, h.WindowTurns - 1); }

function startHazard(i){
  S.act = i < 4 ? 1 : 2;
  S.hazard = i; S.hzTurn = 0; S.hzFails = 0; S.mode = "hazard";
  const h = DT.hazards[i];
  clearSay();
  say("<span class='sys'>Day " + h.Day + ", Act " + h.Act + ". " + h.Location + "</span>");
  say(h.PlayerSees);
  drawHazard();
}

function drawHazard(){
  if(typeof document === "undefined") return;
  const h = DT.hazards[S.hazard];
  hud([["day", h.Day], ["act", h.Act], ["encounter", (S.hazard+1) + "/" + DT.hazards.length],
       ["turn", S.hzTurn + "/" + h.WindowTurns], ["condition", S.limping ? "limping" : "sound"]]);
  const tt = telegraphTurn(h);
  let body = "<div class='sys'>Pursuer: " + h.PursuerType + "</div>";
  body += "<div class='sys' style='margin-top:6px'>Teaches: " + h.Teaches + "</div>";
  if(S.hzTurn === tt) body = "<div class='rex' style='font-size:16px'>&gt; " + h.Telegraph + "</div>" + body;
  $("stage").innerHTML = body +
    "<div class='btns'><button onclick='hz(\"wait\")'>Hold still</button>" +
    "<button onclick='hz(\"go\")'>Break for it</button></div>";
}

function hz(choice){
  const h = DT.hazards[S.hazard];
  const tt = telegraphTurn(h);
  if(choice === "go"){
    if(S.hzTurn === tt + 1){ hazardWin(h); return; }
    hazardFail(h, S.hzTurn <= tt ? "You went before the tell finished." :
                                   "You went late. The window had closed.");
    return;
  }
  S.hzTurn++;
  if(S.hzTurn > h.WindowTurns){ hazardFail(h, "You held too long."); return; }
  drawHazard();
}

function hazardWin(h){
  say("<span class='win'>Clear.</span> " + h.EscapeCondition, "");
  const next = S.hazard + 1;
  $("stage").innerHTML = "<div class='btns'><button onclick='" +
    (next < DT.hazards.length ? "startHazard(" + next + ")" : "beginFight()") +
    "'>" + (next < DT.hazards.length ? "Keep going" : "Day 8. The street you know.") +
    "</button></div>";
}

function hazardFail(h, why){
  S.hzFails++; S.totalFails++;
  let extra = "";
  if(h.CausesCondition && !S.limping){ S.limping = true; extra = " The back leg has opinions now."; }
  say("<span class='lose'>Caught.</span> " + why + " " + h.FailCondition + extra);
  S.hzTurn = 0;
  $("stage").innerHTML = "<div class='btns'><button onclick='drawHazard()'>Again</button></div>";
}

// ------------------------------------------------------------------- ACT 3
function beginFight(){
  S.act = 3; S.mode = "fight"; S.over = false;
  S.stamina = 17 - Math.min(S.totalFails, 3);   // 17 clean, 14 floor
  S.dog = [0,0]; S.rex = [5,5]; S.round = 0; S.charge = START_CHARGE;
  S.moves = []; S.lastCat = null; S.phaseIx = 0; S.attempts++; S.spoken = []; S.log = [];
  S.checkpoint = null;
  clearSay();
  const p = DT.phases[0];
  say("<span class='sys'>Act 3. " + p.ArenaName + ". " + p.Light + "</span>");
  say(p.PlayerSees);
  if(S.limping) say("<span class='sys'>You arrive limping. It can see that.</span>");
  say("<span class='sys'>Reach the kid before the clock or your legs run out. " +
      "Arrow keys or WASD to move, E to wait.</span>");
  if(S.priorAttempt) fireRetryLine();
  drawFight();
}

function phase(){ return DT.phases[S.phaseIx]; }
function approach(){ return Math.max(0, Math.min(1, 1 - man(S.dog, S.kid) / S.distMax)); }
function band(){ return S.charge > BAND_CLIN ? "clinical" : (S.charge >= BAND_CONF ? "confident" : "strained"); }
function inBounds(t){ const p = phase(); const [w,h] = p.GridSpan.toLowerCase().split("x").map(Number);
                      return t[0]>=0 && t[0]<w && t[1]>=0 && t[1]<h; }

function drawFight(){
  if(typeof document === "undefined") return;
  const p = phase();
  const [w,h] = p.GridSpan.toLowerCase().split("x").map(Number);
  hud([["phase", p.PhaseIndex + "/3 " + p.ArenaName], ["round", S.round + "/" + MAXROUNDS],
       ["stamina", S.stamina], ["approach", approach().toFixed(2)],
       ["charge", Math.round(S.charge) + "%"], ["register", band()]]);
  let t = "<table class='grid'>";
  for(let y=0;y<h;y++){
    t += "<tr>";
    for(let x=0;x<w;x++){
      const c=[x,y]; let cls="", ch="&middot;";
      if(eq(c,S.dog)){cls="dog";ch="DOG";}
      else if(eq(c,S.rex)){cls="rexT";ch="REX";}
      else if(eq(c,S.kid)){cls="kid";ch="KID";}
      else if((p.CoverTiles||[]).some(e=>eq(e,c))){cls="cover";ch="#";}
      else if((p.ExitTiles||[]).some(e=>eq(e,c))){cls="exit";ch="=";}
      t += "<td class='"+cls+"'>"+ch+"</td>";
    }
    t += "</tr>";
  }
  t += "</table>";
  t += "<div class='pad'>" +
       "<button class='key' onclick=\"mv('up')\">W</button>" +
       "<button class='key' onclick=\"mv('left')\">A</button>" +
       "<button class='key' onclick=\"mv('wait')\">E</button>" +
       "<button class='key' onclick=\"mv('right')\">D</button>" +
       "<button class='key' onclick=\"mv('down')\" style='grid-column:2'>S</button></div>";
  $("stage").innerHTML = t;
}

function hud(pairs){
  if(typeof document === "undefined") return;
  $("hud").innerHTML = pairs.map(([k,v]) => "<span>" + k + " <b>" + v + "</b></span>").join("");
}

// --- the dog's observables, ported from game/rex/dog.py ---
function recentMoves(){ return S.moves.slice(-WINDOW); }
function dirFreq(){
  const span = S.moves.slice(-FREQ).filter(m => STEP[m]);
  const out = {left:0,right:0,up:0,down:0};
  if(!span.length) return out;
  for(const m of span) out[m]++;
  for(const k in out) out[k] = out[k] / span.length;
  return out;
}
function periodicity(){
  const span = S.moves.slice(-FREQ);
  if(span.length < 4) return 0;
  let best = 0;
  for(let lag=2; lag<6; lag++){
    let hits = 0, n = 0;
    for(let i=lag;i<span.length;i++){ n++; if(span[i] === span[i-lag]) hits++; }
    if(n) best = Math.max(best, hits/n);
  }
  return best;
}

// --- the Nemesis, ported from game/rex/nemesis.py ---
function predict(){
  const w = recentMoves().filter(m => STEP[m]);
  if(!w.length) return S.dog.slice();
  const c = {};
  for(const m of w) c[m] = (c[m]||0)+1;
  const best = Object.keys(c).sort((a,b)=>c[b]-c[a])[0];
  return [S.dog[0]+STEP[best][0], S.dog[1]+STEP[best][1]];
}
function stepToward(from, target){
  let best = from, bd = man(from, target);
  for(const d in STEP){
    const c = [from[0]+STEP[d][0], from[1]+STEP[d][1]];
    if(!inBounds(c)) continue;
    if(man(c, target) < bd){ best = c; bd = man(c, target); }
  }
  return best;
}
function rexAct(){
  const predicted = predict();
  const before = man(S.rex, S.dog);
  let move = stepToward(S.rex, predicted);
  if(man(move, S.dog) > before) move = stepToward(S.rex, S.dog);  // GDD 6.1 veto
  const moved = !eq(move, S.rex);
  S.rex = move;
  S.charge = Math.max(0, Math.min(START_CHARGE, S.charge - (moved ? PURSUIT : HOLD) + SOLAR));
  return predicted;
}
function firingCategories(){
  // Every trigger that fires this round, in GDD 4 priority order. A5 returned
  // only the first, so one category dominated and suppression ate the rest:
  // a winning run surfaced 2 lines out of 24. Returning the whole set lets the
  // speaker fall through to the next live trigger instead of going quiet.
  const out = [], f = dirFreq();
  if(periodicity() >= 0.6) out.push("periodicity_called");
  if(Math.max(f.left,f.right,f.up,f.down) >= 0.45) out.push("sealing_direction");
  if(S.moves.slice(-4).filter(m=>m==="wait").length >= 2) out.push("stall_detected");
  if((phase().CoverTiles||[]).some(c=>eq(c,S.dog))) out.push("cover_habit");
  if((phase().ExitTiles||[]).some(e=>man(S.dog,e)<=2)) out.push("exit_fixation");
  if(S.charge < BAND_CONF) out.push("charge_strain");
  if(S.limping) out.push("gait_read");
  return out;
}
const COMPASS = ["left","right","up","down"];
function namesDirection(line){
  return COMPASS.filter(d => new RegExp("\\b" + d + "\\b", "i").test(line));
}
function dominantDir(){
  const f = dirFreq();
  let best = null, bv = -1;
  for(const d of COMPASS) if(f[d] > bv){ bv = f[d]; best = d; }
  return bv > 0 ? best : null;
}
function speakRead(){
  // GDD 4 suppression: never the same category twice running. With the full
  // firing set we can honour that and still speak, by taking the next live
  // trigger down the ladder.
  for(const cat of firingCategories()){
    if(cat === S.lastCat) continue;
    const row = DT.DT_NemesisReads.find(r => r.ReadCategory===cat && r.ChargeBand===band());
    if(!row || S.spoken.includes(row.Line)) continue;   // never twice in one run
    // RM-001, found by qa/adversary.js: the generated lines for
    // sealing_direction all name "left", but the trigger fires whenever any
    // one direction dominates. The robot was telling a right-running dog it
    // favoured left. A read that misreports the observable it cites is worse
    // than silence, so the line is held back unless the direction matches.
    const named = namesDirection(row.Line);
    if(named.length && !named.includes(dominantDir())) continue;
    S.lastCat = cat;
    S.spoken.push(row.Line);
    say("<span class='rex'>REX: &ldquo;" + row.Line + "&rdquo;</span>");
    return;
  }
}
function fireRetryLine(){
  const rows = DT.DT_RetryReads.filter(r => r.Gate === S.priorAttempt);
  const row = rows.find(r => r.ChargeBand === band()) || rows[0];
  if(row){ S.spoken.push(row.Line);
           say("<span class='rex'>REX: &ldquo;" + row.Line + "&rdquo;</span>"); }
}

function mv(dir){
  if(S.over || S.mode !== "fight") return;
  if(dir !== "wait"){
    const t = [S.dog[0]+STEP[dir][0], S.dog[1]+STEP[dir][1]];
    if(!inBounds(t)){
      // RM-003, found by qa/adversary.js: a rejected move changed nothing at
      // all, so a player holding a key at the edge saw a frozen game.
      say("<span class='sys'>The fence is there. Nothing on that side.</span>");
      return;
    }
    S.dog = t;
  }
  S.moves.push(dir);
  S.round++;
  rexAct();
  speakRead();
  // RM-002, found by qa/adversary.js: the adjacency drain could take stamina
  // to -1 and the HUD showed it. Empty is empty.
  S.stamina = Math.max(0, S.stamina - 1 - (man(S.rex, S.dog) <= 1 ? 1 : 0));
  checkGate();
  drawFight();
  checkEnd();
}
function checkGate(){
  const a = approach();
  let ix = 0;
  for(let i=0;i<DT.phases.length;i++){
    const p = DT.phases[i];
    if(a >= p.ApproachLow && (a < p.ApproachHigh || p.PhaseIndex === 3)) ix = i;
  }
  if(ix !== S.phaseIx){
    S.phaseIx = ix;
    S.checkpoint = {phase: ix, moves: S.moves.slice(), dog: S.dog.slice()};
    const p = phase();
    say("<span class='sys'>&gt;&gt;&gt; The arena advances. " + p.ArenaName + ".</span>");
    say("<span class='sys'>" + p.Light + "</span>");
  }
}
function checkEnd(){
  if(approach() >= 1){
    S.over = true;
    say("<span class='win'>She sees you. The robot goes still.</span>");
    $("stage").innerHTML += "<div class='btns'><button onclick='location.reload()'>Again from the shelter</button></div>";
  } else if(S.stamina <= 0 || S.round >= MAXROUNDS){
    S.over = true;
    S.priorAttempt = phase().PhaseID.replace("phase_","");
    say("<span class='lose'>The porch light is still on. You cannot reach it.</span>");
    $("stage").innerHTML += "<div class='btns'><button onclick='beginFight()'>Retry from the gate</button></div>";
  }
}

if (typeof document !== "undefined") document.addEventListener("keydown", e => {
  const k = {w:"up",a:"left",s:"down",d:"right",e:"wait",
             ArrowUp:"up",ArrowLeft:"left",ArrowDown:"down",ArrowRight:"right"}[e.key];
  if(k && S.mode === "fight"){ e.preventDefault(); mv(k); }
});
if (typeof document !== "undefined") boot();

// Headless entry point for tests/sim.js. The browser ignores this.
if (typeof module !== "undefined" && module.exports) {
  module.exports = { S, DT, STEP, MAXROUNDS, man, eq, approach, band, inBounds,
                     predict, stepToward, rexAct, firingCategories, mv, beginFight,
                     drawFight, checkEnd, telegraphTurn, hz, startHazard,
                     dirFreq, periodicity, setSinks, speakRead, fireRetryLine,
                     namesDirection, dominantDir };
}
