"use strict";
// ---------------------------------------------------------------------------
// Every line of content below is loaded from data/*.json. Those files are
// copied byte for byte from the pipeline runs by tools/sync_datatables.py.
// Nothing in this file authors game content.
// ---------------------------------------------------------------------------
const DT = {};
let SINK = null;   // tests replace this; the browser leaves it null
function setSinks(s){ SINK = s; }
const $ = id => SINK ? SINK(id) : document.getElementById(id);

const S = {
  act: 1, hazard: 0, hzTurn: 0, hzFails: 0, totalFails: 0,
  limping: false, phaseIx: 0, over: false, mode: "boot",
  // act 3
  dog: [0,0], rex: [5,5], kid: [7,4], distMax: 11,
  stamina: 15, round: 0, charge: 100, moves: [], lastCat: null,
  priorAttempt: null, attempts: 0, checkpoint: null, spoken: [], log: [], log: []
};

const MAXROUNDS = 15, START_CHARGE = 100, PURSUIT = 8, HOLD = 1, SOLAR = 2;
const BAND_CLIN = 60, BAND_CONF = 30, WINDOW = 4, FREQ = 20;
const STEP = {left:[-1,0], right:[1,0], up:[0,-1], down:[0,1]};

const man = (a,b) => Math.abs(a[0]-b[0]) + Math.abs(a[1]-b[1]);
const eq = (a,b) => a[0]===b[0] && a[1]===b[1];

function say(html, cls){
  S.log.push(String(html).replace(/<[^>]*>/g, ""));   // visible to headless tests
  if(typeof document === "undefined"){ return; }
  const p = document.createElement("p");
  if(cls) p.className = cls;
  p.innerHTML = html;
  if(html.indexOf("class='rex'") >= 0 && S.mode === "fight"){
    BOARD.bubble = String(html).replace(/<[^>]*>/g, "").replace(/^REX:\s*/, "")
      .replace(/&ldquo;|&rdquo;/g, "“").replace(/&amp;/g, "&");
    BOARD.bubbleT0 = performance.now();
  }
  $("say").appendChild(p);
  while($("say").children.length > 4) $("say").removeChild($("say").firstChild);
}
function clearSay(){ if(typeof document === "undefined") return; $("say").innerHTML = ""; }

// A muted line under the stage naming the course work that made what is on
// screen. It is for a reader who has two minutes and seventy other games: the
// mechanics say what the agents do, this says which agent did it.
const BADGE = {
  hazard: "<b>Where the course shows up.</b> This encounter, its telegraph, its escape window " +
          "and what failing it costs came from a RAG pipeline over the design document and " +
          "story bible (A4). The narration voice was enforced by a style-guide agent (A7). " +
          "Nothing here was typed into the game.",
  fight:  "<b>Where the course shows up.</b> REX is the Nemesis, a goal-oriented agent: it " +
          "perceives your last four moves, predicts your next tile, moves to intercept it, and " +
          "vetoes its own prediction when that would lose ground (A5). Every line it speaks is " +
          "a RAG-generated read keyed by charge register (A4). If you lose, its first line back " +
          "names the gate you died at, from a generate-evaluate-refine loop (A6). This build was " +
          "attacked by an adversarial QA agent that found three real bugs, all fixed (A9)."
};
function badge(kind){ if(typeof document === "undefined") return; $("badge").innerHTML = BADGE[kind] || ""; }

// ---------------------------------------------------------------------- boot
async function boot(){
  const names = ["DT_JourneyHazards","DT_ArenaPhases","DT_NemesisReads",
                 "DT_RetryReads","DT_JourneyBeats","MANIFEST"];
  for(const n of names){
    const r = await fetch("data/" + n + ".json");
    DT[n] = await r.json();
  }
  DT.hazards = DT.DT_JourneyHazards.slice().sort((a,b)=>a.Day-b.Day);
  DT.phases  = DT.DT_ArenaPhases.slice().sort((a,b)=>a.PhaseIndex-b.PhaseIndex);
  const rows = DT.MANIFEST.reduce((n,m)=>n+m.rows,0);
  $("prov").innerHTML = "All content generated by the Rex Machina agent pipelines. " +
    rows + " rows across " + DT.MANIFEST.length + " DataTables, loaded unmodified from <code>data/</code>.";
  intro();
}

// The first screen. A grader with two minutes needs to reach the fight, and
// the journey takes longer than that when played properly, so the fight is one
// click away from the start. Skipping it costs nothing but the stamina bonus.
function intro(){
  S.mode = "intro";
  if(typeof document === "undefined") return;
  hud([["day", 0], ["act", "-"], ["condition", "sound"]]);
  clearSay();
  say("<span class='sys'>A shelter dog walks nine days home to the family that gave her away, " +
      "and finds a robot dog in her place.</span>");
  say("<span class='sys'>Acts 1 and 2: six chases. Read the tell, break on the turn after it. " +
      "Act 3: the robot does not chase you. It moves to where it thinks you are about to go, " +
      "and tells you what it measured off your movement.</span>");
  $("stage").innerHTML =
    "<div class='intro'>" +
    "<div class='btns'>" +
    "<button onclick='startHazard(0)'>Start from the shelter &middot; about 6 minutes</button>" +
    "<button onclick='beginFight()'>Skip to the fight &middot; about 2 minutes</button></div>" +
    "<div class='hint'>Arrow keys or WASD in the fight, E to wait. Everything else is a button.</div>" +
    "<h2 style='margin-top:16px'>What made this</h2>" +
    "<ul>" +
    "<li><b>Every line and every number</b> in the game was generated by agent pipelines. " +
    "The game code contains no content.</li>" +
    "<li><b>REX</b>, the robot, is a goal-oriented agent: perception, prediction, intercept, veto.</li>" +
    "<li><b>Its reads</b> are RAG output over the design document, keyed by how much charge it has left.</li>" +
    "<li><b>Its retry lines</b> come from a generate, evaluate, refine loop with a circuit breaker.</li>" +
    "<li><b>The journey narration</b> was scored and rewritten by a style-guide agent.</li>" +
    "<li><b>The build was attacked</b> by an adversarial QA agent. It found three bugs; they are fixed.</li>" +
    "</ul></div>";
  badge("");
}

// ------------------------------------------------------------- ACTS 1 and 2
// Six generated encounters. Each row carries a Telegraph, a WindowTurns count
// and an EscapeCondition: move on the turn after the tell, not before.
function telegraphTurn(h){ return Math.max(1, h.WindowTurns - 1); }

function startHazard(i){
  S.act = i < 4 ? 1 : 2;
  S.hazard = i; S.hzTurn = 0; S.hzFails = 0; S.mode = "hazard";
  const h = DT.hazards[i];
  clearSay();
  say("<span class='sys'>Day " + h.Day + ", Act " + h.Act + ". " + h.Location + "</span>");
  say(h.PlayerSees);
  drawHazard();
}

function drawHazard(){
  if(typeof document === "undefined") return;
  const h = DT.hazards[S.hazard];
  hud([["day", h.Day], ["act", h.Act], ["encounter", (S.hazard+1) + "/" + DT.hazards.length],
       ["turn", S.hzTurn + "/" + h.WindowTurns], ["condition", S.limping ? "limping" : "sound"]]);
  const tt = telegraphTurn(h);
  let body = "<div class='sys'>Pursuer: " + h.PursuerType + "</div>";
  body += "<div class='sys' style='margin-top:6px'>Teaches: " + h.Teaches + "</div>";
  if(S.hzTurn === tt) body = "<div class='rex' style='font-size:16px'>&gt; " + h.Telegraph + "</div>" + body;
  // What holding still is for. Without this a first click on Break is a loss
  // with no idea why, which is a bad first thirty seconds.
  const hint = S.hzTurn === tt
    ? "That is the tell. Break for it on this next turn."
    : S.hzTurn < tt
      ? "Hold still until the tell appears in orange, then break on the very next turn. " +
        "Too early or too late and you are caught."
      : "The tell has passed. Break now or lose the window.";
  $("stage").innerHTML = body +
    "<div class='btns'><button onclick='hz(\"wait\")'>Hold still</button>" +
    "<button onclick='hz(\"go\")'>Break for it</button>" +
    "<button onclick='beginFight()' style='margin-left:auto;opacity:.7'>Skip to the fight</button></div>" +
    "<div class='hint'>" + hint + "</div>";
  badge("hazard");
}

function hz(choice){
  const h = DT.hazards[S.hazard];
  const tt = telegraphTurn(h);
  if(choice === "go"){
    if(S.hzTurn === tt + 1){ hazardWin(h); return; }
    hazardFail(h, S.hzTurn <= tt ? "You went before the tell finished." :
                                   "You went late. The window had closed.");
    return;
  }
  S.hzTurn++;
  if(S.hzTurn > h.WindowTurns){ hazardFail(h, "You held too long."); return; }
  drawHazard();
}

function hazardWin(h){
  say("<span class='win'>Clear.</span> " + h.EscapeCondition, "");
  const next = S.hazard + 1;
  $("stage").innerHTML = "<div class='btns'><button onclick='" +
    (next < DT.hazards.length ? "startHazard(" + next + ")" : "beginFight()") +
    "'>" + (next < DT.hazards.length ? "Keep going" : "Day 8. The street you know.") +
    "</button></div>";
}

function hazardFail(h, why){
  S.hzFails++; S.totalFails++;
  let extra = "";
  if(h.CausesCondition && !S.limping){ S.limping = true; extra = " The back leg has opinions now."; }
  say("<span class='lose'>Caught.</span> " + why + " " + h.FailCondition + extra);
  S.hzTurn = 0;
  $("stage").innerHTML = "<div class='btns'><button onclick='drawHazard()'>Again</button></div>";
}

// ------------------------------------------------------------------- ACT 3
function beginFight(){
  S.act = 3; S.mode = "fight"; S.over = false;
  S.stamina = 17 - Math.min(S.totalFails, 3);   // 17 clean, 14 floor
  S.dog = [0,0]; S.rex = [5,5]; S.round = 0; S.charge = START_CHARGE;
  S.moves = []; S.lastCat = null; S.phaseIx = 0; S.attempts++; S.spoken = []; S.log = [];
  S.checkpoint = null; S.predicted = null;
  clearSay();
  const p = DT.phases[0];
  say("<span class='sys'>Act 3. " + p.ArenaName + ". " + p.Light + "</span>");
  say(p.PlayerSees);
  if(S.limping) say("<span class='sys'>You arrive limping. It can see that.</span>");
  say("<span class='sys'>Reach the kid before the clock or your legs run out. " +
      "Arrow keys or WASD to move, E to wait.</span>");
  if(S.priorAttempt) fireRetryLine();
  drawFight();
}

function phase(){ return DT.phases[S.phaseIx]; }
function approach(){ return Math.max(0, Math.min(1, 1 - man(S.dog, S.kid) / S.distMax)); }
function band(){ return S.charge > BAND_CLIN ? "clinical" : (S.charge >= BAND_CONF ? "confident" : "strained"); }
function inBounds(t){ const p = phase(); const [w,h] = p.GridSpan.toLowerCase().split("x").map(Number);
                      return t[0]>=0 && t[0]<w && t[1]>=0 && t[1]<h; }

function drawFight(){
  if(typeof document === "undefined") return;
  const p = phase();
  const [w,h] = p.GridSpan.toLowerCase().split("x").map(Number);
  hud([["phase", p.PhaseIndex + "/3 " + p.ArenaName], ["round", S.round + "/" + MAXROUNDS],
       ["stamina", S.stamina], ["approach", approach().toFixed(2)],
       ["charge", Math.round(S.charge) + "%"], ["register", band()]]);
  const T = BOARD.T;
  let t = "<div class='boardwrap'><canvas id='board' width='" + (w*T) + "' height='" + (h*T) + "'></canvas></div>";
  t += "<div class='legend'>" +
       "<span><i class='sw you'></i>you, the dog</span>" +
       "<span><i class='sw rex'></i>REX, the robot</span>" +
       "<span><i class='sw pred'></i>where REX thinks you will step</span>" +
       "<span><i class='sw kid'></i>the kid: reach her</span>" +
       "<span><i class='sw cover'></i>cover</span></div>";
  // Explicit grid areas: auto-placement put the left arrow in the top row.
  t += "<div class='pad'>" +
       "<button class='key' style='grid-area:1/2' onclick=\"mv('up')\">&uarr;</button>" +
       "<button class='key' style='grid-area:2/1' onclick=\"mv('left')\">&larr;</button>" +
       "<button class='key' style='grid-area:2/2' onclick=\"mv('wait')\">wait</button>" +
       "<button class='key' style='grid-area:2/3' onclick=\"mv('right')\">&rarr;</button>" +
       "<button class='key' style='grid-area:3/2' onclick=\"mv('down')\">&darr;</button></div>";
  t += "<div class='hint'>Tap a tile next to the dog, or use the arrows. " +
       "REX moves to the tile it thinks you will step on next; repeat a direction and it will be " +
       "waiting there. Stamina drops faster while it is next to you.<br>" +
       "It speaks only when it has measured something. To hear it: go left three times, " +
       "wait twice, or stand on cover.</div>";
  $("stage").innerHTML = t;
  badge("fight");
  boardSync();
}

function hud(pairs){
  if(typeof document === "undefined") return;
  $("hud").innerHTML = pairs.map(([k,v]) => "<span>" + k + " <b>" + v + "</b></span>").join("");
}

// --- the dog's observables, ported from game/rex/dog.py ---
function recentMoves(){ return S.moves.slice(-WINDOW); }
function dirFreq(){
  const span = S.moves.slice(-FREQ).filter(m => STEP[m]);
  const out = {left:0,right:0,up:0,down:0};
  if(!span.length) return out;
  for(const m of span) out[m]++;
  for(const k in out) out[k] = out[k] / span.length;
  return out;
}
function periodicity(){
  const span = S.moves.slice(-FREQ);
  if(span.length < 4) return 0;
  let best = 0;
  for(let lag=2; lag<6; lag++){
    let hits = 0, n = 0;
    for(let i=lag;i<span.length;i++){ n++; if(span[i] === span[i-lag]) hits++; }
    if(n) best = Math.max(best, hits/n);
  }
  return best;
}

// --- the Nemesis, ported from game/rex/nemesis.py ---
function predict(){
  const w = recentMoves().filter(m => STEP[m]);
  if(!w.length) return S.dog.slice();
  const c = {};
  for(const m of w) c[m] = (c[m]||0)+1;
  const best = Object.keys(c).sort((a,b)=>c[b]-c[a])[0];
  return [S.dog[0]+STEP[best][0], S.dog[1]+STEP[best][1]];
}
function stepToward(from, target){
  let best = from, bd = man(from, target);
  for(const d in STEP){
    const c = [from[0]+STEP[d][0], from[1]+STEP[d][1]];
    if(!inBounds(c)) continue;
    if(man(c, target) < bd){ best = c; bd = man(c, target); }
  }
  return best;
}
function rexAct(){
  const predicted = predict();
  const before = man(S.rex, S.dog);
  let move = stepToward(S.rex, predicted);
  if(man(move, S.dog) > before) move = stepToward(S.rex, S.dog);  // GDD 6.1 veto
  const moved = !eq(move, S.rex);
  S.rex = move;
  S.predicted = predicted;   // drawn on the grid, so the guess is visible
  S.charge = Math.max(0, Math.min(START_CHARGE, S.charge - (moved ? PURSUIT : HOLD) + SOLAR));
  return predicted;
}
function firingCategories(){
  // Every trigger that fires this round, in GDD 4 priority order. A5 returned
  // only the first, so one category dominated and suppression ate the rest:
  // a winning run surfaced 2 lines out of 24. Returning the whole set lets the
  // speaker fall through to the next live trigger instead of going quiet.
  const out = [], f = dirFreq();
  if(periodicity() >= 0.6) out.push("periodicity_called");
  if(Math.max(f.left,f.right,f.up,f.down) >= 0.45) out.push("sealing_direction");
  if(S.moves.slice(-4).filter(m=>m==="wait").length >= 2) out.push("stall_detected");
  if((phase().CoverTiles||[]).some(c=>eq(c,S.dog))) out.push("cover_habit");
  if((phase().ExitTiles||[]).some(e=>man(S.dog,e)<=2)) out.push("exit_fixation");
  if(S.charge < BAND_CONF) out.push("charge_strain");
  if(S.limping) out.push("gait_read");
  return out;
}
const COMPASS = ["left","right","up","down"];
function namesDirection(line){
  return COMPASS.filter(d => new RegExp("\\b" + d + "\\b", "i").test(line));
}
function dominantDir(){
  const f = dirFreq();
  let best = null, bv = -1;
  for(const d of COMPASS) if(f[d] > bv){ bv = f[d]; best = d; }
  return bv > 0 ? best : null;
}
function speakRead(){
  // GDD 4 suppression: never the same category twice running. With the full
  // firing set we can honour that and still speak, by taking the next live
  // trigger down the ladder.
  for(const cat of firingCategories()){
    if(cat === S.lastCat) continue;
    const row = DT.DT_NemesisReads.find(r => r.ReadCategory===cat && r.ChargeBand===band());
    if(!row || S.spoken.includes(row.Line)) continue;   // never twice in one run
    // RM-001, found by qa/adversary.js: the generated lines for
    // sealing_direction all name "left", but the trigger fires whenever any
    // one direction dominates. The robot was telling a right-running dog it
    // favoured left. A read that misreports the observable it cites is worse
    // than silence, so the line is held back unless the direction matches.
    const named = namesDirection(row.Line);
    if(named.length && !named.includes(dominantDir())) continue;
    S.lastCat = cat;
    S.spoken.push(row.Line);
    say("<span class='rex'>REX: &ldquo;" + row.Line + "&rdquo;</span>");
    return;
  }
}
function fireRetryLine(){
  const rows = DT.DT_RetryReads.filter(r => r.Gate === S.priorAttempt);
  const row = rows.find(r => r.ChargeBand === band()) || rows[0];
  if(row){ S.spoken.push(row.Line);
           say("<span class='rex'>REX: &ldquo;" + row.Line + "&rdquo;</span>"); }
}

function mv(dir){
  if(S.over || S.mode !== "fight") return;
  if(dir !== "wait"){
    const t = [S.dog[0]+STEP[dir][0], S.dog[1]+STEP[dir][1]];
    if(!inBounds(t)){
      // RM-003, found by qa/adversary.js: a rejected move changed nothing at
      // all, so a player holding a key at the edge saw a frozen game.
      say("<span class='sys'>The fence is there. Nothing on that side.</span>");
      return;
    }
    S.dog = t;
  }
  S.moves.push(dir);
  S.round++;
  rexAct();
  speakRead();
  // RM-002, found by qa/adversary.js: the adjacency drain could take stamina
  // to -1 and the HUD showed it. Empty is empty.
  S.stamina = Math.max(0, S.stamina - 1 - (man(S.rex, S.dog) <= 1 ? 1 : 0));
  checkGate();
  drawFight();
  checkEnd();
}
function checkGate(){
  const a = approach();
  let ix = 0;
  for(let i=0;i<DT.phases.length;i++){
    const p = DT.phases[i];
    if(a >= p.ApproachLow && (a < p.ApproachHigh || p.PhaseIndex === 3)) ix = i;
  }
  if(ix !== S.phaseIx){
    S.phaseIx = ix;
    S.checkpoint = {phase: ix, moves: S.moves.slice(), dog: S.dog.slice()};
    const p = phase();
    say("<span class='sys'>&gt;&gt;&gt; The arena advances. " + p.ArenaName + ".</span>");
    say("<span class='sys'>" + p.Light + "</span>");
  }
}
function checkEnd(){
  if(approach() >= 1){
    S.over = true;
    say("<span class='win'>She sees you. The robot goes still.</span>");
    $("stage").innerHTML += "<div class='btns'><button onclick='location.reload()'>Again from the shelter</button></div>";
  } else if(S.stamina <= 0 || S.round >= MAXROUNDS){
    S.over = true;
    S.priorAttempt = phase().PhaseID.replace("phase_","");
    say("<span class='lose'>The porch light is still on. You cannot reach it.</span>");
    $("stage").innerHTML += "<div class='btns'><button onclick='beginFight()'>Retry from the gate</button></div>";
  }
}

// ------------------------------------------------------------ the board
// Drawn, not tabulated. The text grid told you which cell said DOG; it did not
// tell you that the dog was you, that the robot was hunting, or that the ×
// was a prediction rather than a wall. Everything below exists so a stranger
// reads the board before reading a word: the piece with the ring is you, the
// grey angular one with the red eye is the machine, the small figure on the
// lit square is where you are going. Pieces slide between tiles so a move is
// something you watch, and the robot's line comes out of the robot.
//
// Nothing here changes the game. S is read, never written; mv() is the only
// way the board affects the fight, and it is the same mv() the keys call.
const BOARD = {
  T: 44, running: false, dog: null, rex: null, dogFrom: null, rexFrom: null,
  t0: 0, dur: 220, dogFace: 1, rexFace: -1, bubble: null, bubbleT0: 0, canvas: null
};

function boardSync(){
  // Called after every redraw. Remembers where the pieces were drawn last so
  // the next paint can slide them from there to where the state says they are.
  const c = $("board");
  if(!c) return;
  if(!BOARD.dog){ BOARD.dog = S.dog.slice(); BOARD.rex = S.rex.slice(); }
  if(!eq(BOARD.dog, S.dog) || !eq(BOARD.rex, S.rex)){
    BOARD.dogFrom = BOARD.dog.slice(); BOARD.rexFrom = BOARD.rex.slice();
    if(S.dog[0] !== BOARD.dog[0]) BOARD.dogFace = Math.sign(S.dog[0] - BOARD.dog[0]);
    if(S.rex[0] !== BOARD.rex[0]) BOARD.rexFace = Math.sign(S.rex[0] - BOARD.rex[0]);
    BOARD.dog = S.dog.slice(); BOARD.rex = S.rex.slice();
    BOARD.t0 = performance.now();
  }
  if(BOARD.canvas !== c){
    BOARD.canvas = c;
    c.addEventListener("click", ev => {
      const r = c.getBoundingClientRect();
      const x = Math.floor((ev.clientX - r.left) / r.width  * c.width  / BOARD.T);
      const y = Math.floor((ev.clientY - r.top)  / r.height * c.height / BOARD.T);
      const dx = x - S.dog[0], dy = y - S.dog[1];
      if(dx === 0 && dy === 0) mv("wait");
      else if(Math.abs(dx) + Math.abs(dy) === 1) mv(dx === 1 ? "right" : dx === -1 ? "left" : dy === 1 ? "down" : "up");
    });
  }
  if(!BOARD.running){ BOARD.running = true; requestAnimationFrame(paint); }
}

function lerpPos(from, to, k){
  if(!from) return to;
  return [from[0] + (to[0]-from[0]) * k, from[1] + (to[1]-from[1]) * k];
}
function ease(k){ return k < 0.5 ? 2*k*k : 1 - Math.pow(-2*k+2, 2)/2; }

function paint(now){
  const c = $("board");
  if(!c || S.mode !== "fight"){ BOARD.running = false; return; }
  const g = c.getContext("2d"), T = BOARD.T, p = phase();
  const [w,h] = p.GridSpan.toLowerCase().split("x").map(Number);
  const k = ease(Math.min(1, (now - BOARD.t0) / BOARD.dur));
  const dogPos = lerpPos(BOARD.dogFrom, BOARD.dog, k);
  const rexPos = lerpPos(BOARD.rexFrom, BOARD.rex, k);

  // floor: a yard at night, two greys, a hair of grid
  for(let y=0;y<h;y++) for(let x=0;x<w;x++){
    g.fillStyle = (x+y)%2 ? "#1b2025" : "#161a1f";
    g.fillRect(x*T, y*T, T, T);
  }
  g.strokeStyle = "#0e1114"; g.lineWidth = 1;
  for(let i=0;i<=w;i++){ g.beginPath(); g.moveTo(i*T+.5,0); g.lineTo(i*T+.5,h*T); g.stroke(); }
  for(let i=0;i<=h;i++){ g.beginPath(); g.moveTo(0,i*T+.5); g.lineTo(w*T,i*T+.5); g.stroke(); }

  // exits and cover, from the phase row
  for(const e of (p.ExitTiles||[])){
    g.strokeStyle = "#3f6f86"; g.setLineDash([4,3]); g.lineWidth = 2;
    g.strokeRect(e[0]*T+5, e[1]*T+5, T-10, T-10); g.setLineDash([]);
  }
  for(const cv of (p.CoverTiles||[])) drawCrate(g, cv[0]*T, cv[1]*T, T);

  // the kid's tile, lit
  const kx = S.kid[0]*T, ky = S.kid[1]*T;
  const grad = g.createRadialGradient(kx+T/2, ky+T/2, 4, kx+T/2, ky+T/2, T*0.9);
  grad.addColorStop(0, "rgba(224,163,74,.35)"); grad.addColorStop(1, "rgba(224,163,74,0)");
  g.fillStyle = grad; g.fillRect(kx-T/2, ky-T/2, T*2, T*2);
  drawKid(g, kx, ky, T);

  // the prediction, pulsing so it reads as a guess and not as a wall
  if(S.predicted && !eq(S.predicted, S.rex)){
    const pulse = 0.55 + 0.45 * Math.sin(now / 260);
    const px = S.predicted[0]*T, py = S.predicted[1]*T;
    g.strokeStyle = "rgba(111,168,199," + (0.35 + 0.5*pulse) + ")"; g.lineWidth = 2;
    g.strokeRect(px+4, py+4, T-8, T-8);
    g.beginPath(); g.moveTo(px+13, py+13); g.lineTo(px+T-13, py+T-13);
    g.moveTo(px+T-13, py+13); g.lineTo(px+13, py+T-13); g.stroke();
  }

  drawRex(g, rexPos[0]*T, rexPos[1]*T, T, BOARD.rexFace);
  drawDog(g, dogPos[0]*T, dogPos[1]*T, T, BOARD.dogFace);

  // labels: the one thing the text grid never managed
  label(g, "YOU", dogPos[0]*T + T/2, dogPos[1]*T - 3, "#7fb069");
  label(g, "REX", rexPos[0]*T + T/2, rexPos[1]*T - 3, "#c9564b");
  label(g, "KID", kx + T/2, ky - 3, "#e0a34a");

  // the read, out of the robot's mouth, for a few seconds
  if(BOARD.bubble && now - BOARD.bubbleT0 < 4200){
    bubble(g, BOARD.bubble, rexPos[0]*T + T/2, rexPos[1]*T, w*T);
  }
  requestAnimationFrame(paint);
}

function label(g, text, x, y, colour){
  // Above the piece, unless the piece is on the top row, where above is off
  // the canvas and the label vanished with it.
  if(y < 16) y += BOARD.T + 16;
  g.font = "bold 10px ui-monospace, Menlo, Consolas, monospace";
  g.textAlign = "center"; g.textBaseline = "bottom";
  g.fillStyle = "rgba(13,15,17,.75)";
  const wdt = g.measureText(text).width + 8;
  g.fillRect(x - wdt/2, y - 12, wdt, 12);
  g.fillStyle = colour; g.fillText(text, x, y - 1);
}

function bubble(g, text, x, y, boardW){
  g.font = "12px ui-monospace, Menlo, Consolas, monospace";
  const pad = 8, maxW = 230;
  // wrap
  const words = text.split(" "), lines = []; let cur = "";
  for(const wd of words){
    const t = cur ? cur + " " + wd : wd;
    if(g.measureText(t).width > maxW - pad*2 && cur){ lines.push(cur); cur = wd; } else cur = t;
  }
  if(cur) lines.push(cur);
  const bw = Math.min(maxW, Math.max(...lines.map(l => g.measureText(l).width)) + pad*2);
  const bh = lines.length * 15 + pad*2;
  let bx = x - bw/2, by = y - bh - 22;
  bx = Math.max(4, Math.min(boardW - bw - 4, bx));
  if(by < 4) by = y + 48;
  g.fillStyle = "rgba(20,24,28,.96)"; g.strokeStyle = "#e0a34a"; g.lineWidth = 1;
  roundRect(g, bx, by, bw, bh, 5); g.fill(); g.stroke();
  g.fillStyle = "#e0a34a"; g.textAlign = "left"; g.textBaseline = "top";
  lines.forEach((l, i) => g.fillText(l, bx + pad, by + pad + i*15));
}

function roundRect(g, x, y, w, h, r){
  g.beginPath(); g.moveTo(x+r, y); g.lineTo(x+w-r, y); g.quadraticCurveTo(x+w, y, x+w, y+r);
  g.lineTo(x+w, y+h-r); g.quadraticCurveTo(x+w, y+h, x+w-r, y+h); g.lineTo(x+r, y+h);
  g.quadraticCurveTo(x, y+h, x, y+h-r); g.lineTo(x, y+r); g.quadraticCurveTo(x, y, x+r, y); g.closePath();
}

function drawCrate(g, x, y, T){
  g.fillStyle = "#4a3a26"; g.fillRect(x+6, y+8, T-12, T-14);
  g.strokeStyle = "#7a5f3a"; g.lineWidth = 1.5; g.strokeRect(x+6.5, y+8.5, T-13, T-15);
  g.beginPath(); g.moveTo(x+6, y+8); g.lineTo(x+T-6, y+T-6); g.moveTo(x+T-6, y+8); g.lineTo(x+6, y+T-6); g.stroke();
}

function drawDog(g, x, y, T, face){
  // a low, long body, a head with two ears, a tail. Warm brown, green ring.
  g.save(); g.translate(x + T/2, y + T/2); g.scale(face || 1, 1);
  g.strokeStyle = "rgba(127,176,105,.9)"; g.lineWidth = 2;
  g.beginPath(); g.arc(0, 2, T*0.42, 0, Math.PI*2); g.stroke();
  g.fillStyle = "#8a5a2b";
  g.beginPath(); g.ellipse(-2, 4, 12, 7, 0, 0, Math.PI*2); g.fill();          // body
  g.fillRect(-11, 8, 3, 6); g.fillRect(-5, 8, 3, 6); g.fillRect(3, 8, 3, 6); g.fillRect(8, 8, 3, 6); // legs
  g.beginPath(); g.arc(11, -2, 6, 0, Math.PI*2); g.fill();                    // head
  g.beginPath(); g.moveTo(7, -7); g.lineTo(9, -13); g.lineTo(12, -6); g.fill(); // ear
  g.beginPath(); g.moveTo(11, -7); g.lineTo(14, -12); g.lineTo(16, -5); g.fill();
  g.strokeStyle = "#8a5a2b"; g.lineWidth = 2.5; g.lineCap = "round";
  g.beginPath(); g.moveTo(-13, 2); g.lineTo(-18, -5); g.stroke();             // tail
  g.fillStyle = "#c9956a"; g.beginPath(); g.arc(15, 0, 2.6, 0, Math.PI*2); g.fill(); // snout
  g.fillStyle = "#111"; g.beginPath(); g.arc(13, -3, 1.2, 0, Math.PI*2); g.fill();   // eye
  g.restore();
}

function drawRex(g, x, y, T, face){
  // the same body plan, squarer, taller, cold, one red visor. Red glow under it.
  g.save(); g.translate(x + T/2, y + T/2);
  const glow = g.createRadialGradient(0, 6, 2, 0, 6, T*0.55);
  glow.addColorStop(0, "rgba(201,86,75,.35)"); glow.addColorStop(1, "rgba(201,86,75,0)");
  g.fillStyle = glow; g.fillRect(-T/2, -T/2, T, T);
  g.scale(face || 1, 1);
  g.fillStyle = "#6f7887";
  g.fillRect(-13, -4, 24, 11);                                                // body
  g.fillStyle = "#4b535f";
  g.fillRect(-12, 7, 4, 8); g.fillRect(-5, 7, 4, 8); g.fillRect(2, 7, 4, 8); g.fillRect(8, 7, 4, 8); // legs
  g.fillRect(-16, -2, 4, 6);                                                  // hip block
  g.fillStyle = "#6f7887"; g.fillRect(8, -13, 12, 10);                       // head
  g.fillStyle = "#ff3b2a"; g.fillRect(14, -10, 6, 3);                        // visor
  g.fillStyle = "#4b535f"; g.fillRect(10, -17, 2, 5);                        // antenna
  g.restore();
}

function drawKid(g, x, y, T){
  g.save(); g.translate(x + T/2, y + T/2);
  g.fillStyle = "#e0a34a"; g.globalAlpha = .25; g.fillRect(-T/2+2, -T/2+2, T-4, T-4); g.globalAlpha = 1;
  g.fillStyle = "#2b2b2b"; g.fillRect(-5, 6, 4, 9); g.fillRect(1, 6, 4, 9);   // legs
  g.fillStyle = "#c9564b"; g.fillRect(-7, -6, 14, 13);                        // jacket
  g.fillRect(-11, -5, 4, 9); g.fillRect(7, -5, 4, 9);                          // arms
  g.fillStyle = "#e8b48a"; g.beginPath(); g.arc(0, -12, 6, 0, Math.PI*2); g.fill(); // head
  g.fillStyle = "#2b2b2b"; g.fillRect(-6, -19, 12, 5);                        // hair
  g.restore();
}

if (typeof document !== "undefined") document.addEventListener("keydown", e => {
  const k = {w:"up",a:"left",s:"down",d:"right",e:"wait",
             ArrowUp:"up",ArrowLeft:"left",ArrowDown:"down",ArrowRight:"right"}[e.key];
  if(k && S.mode === "fight"){ e.preventDefault(); mv(k); }
});
if (typeof document !== "undefined") boot();

// Headless entry point for tests/sim.js. The browser ignores this.
if (typeof module !== "undefined" && module.exports) {
  module.exports = { S, DT, STEP, MAXROUNDS, man, eq, approach, band, inBounds,
                     predict, stepToward, rexAct, firingCategories, mv, beginFight,
                     drawFight, checkEnd, telegraphTurn, hz, startHazard,
                     dirFreq, periodicity, setSinks, speakRead, fireRetryLine,
                     namesDirection, dominantDir };
}
