#!/usr/bin/env python3
"""Proof that the narration answers the ledger and not the last line typed.

Two ledgers, identical except for one decision three days earlier. The same
day-6 scene, the same typed action, both narrated. Whatever differs between
the two outputs can only have come from the ledger.

    python ab_test.py [--live]
"""
import argparse
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from dm import llm, narrate                                   # noqa: E402
from dm.ledger import Ledger                                  # noqa: E402

ROOT = os.path.dirname(os.path.abspath(__file__))
ACTION = "go to the door where the smell is"


def build(took_food):
    led = Ledger()
    led.apply({"add_facts": ["left_behind", "escaped_the_gate"]})
    led.day = 1
    led.apply({"add_facts": ["escaped_alley"]})
    led.day = 3
    if took_food:
        led.apply({"add_facts": ["took_food_from_stranger"],
                   "trust_delta": 1, "hunger_delta": -1})
    else:
        led.apply({"add_facts": ["refused_the_hand"],
                   "trust_delta": -1, "hunger_delta": 1})
    led.day = 4
    led.apply({"condition": "limping"})
    led.day = 6
    return led


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--live", action="store_true")
    args = ap.parse_args()
    prov = llm.provider("live" if args.live else "replay")

    rows = []
    for took in (True, False):
        led = build(took)
        tag = ".ab_%s" % ("took" if took else "refused")
        reply = llm.parse_json(prov.complete(
            "narrate%s" % tag,
            narrate.build_prompt(led, ACTION, ["arrived at the back door"]),
            max_tokens=500))
        rows.append((led, reply["narration"].strip()))

    print("=" * 72)
    print("REACTIVE A/B   provider=%s   same scene, same action" % prov.name)
    print("=" * 72)
    for led, text in rows:
        who = "took_food_from_stranger" if led.has("took_food_from_stranger") \
            else "refused_the_hand"
        print("\n  ledger holds %s, trust %d, hunger %d"
              % (who, led.trust_in_humans, led.hunger))
        print("  %s" % text.replace("\n", " "))

    out = ["# Reactive dialogue, the same scene under two ledgers", "",
           "Generated by `python ab_test.py`. Both runs are day 6 at the diner",
           "back door, both typed `%s`, and both were given the same scene." % ACTION,
           "The two ledgers differ in one decision made on day 3. Everything",
           "that differs below came from the ledger.", ""]
    for led, text in rows:
        who = "took the food on day 3" if led.has("took_food_from_stranger") \
            else "refused the hand on day 3"
        out += ["## The dog who %s" % who, "",
                "trust_in_humans %d, hunger %d, condition %s since day %d"
                % (led.trust_in_humans, led.hunger, led.condition["state"],
                   led.condition["since_day"]), "",
                "> %s" % text.replace("\n", " "), ""]
    out += ["## Ledgers, side by side", "", "```json",
            json.dumps({("took_food" if l.has("took_food_from_stranger")
                         else "refused"): l.as_dict() for l, _ in rows},
                       indent=1), "```", ""]
    open(os.path.join(ROOT, "evidence", "reactive_ab.md"), "w",
         encoding="utf-8").write("\n".join(out) + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
