#!/usr/bin/env python3
"""Exercise every engine-side ledger rule and show it firing.

A rule with unit-test coverage that never fires in a live session is a rule
nobody has watched work. Assignment 6's feedback made that point about a tense
rule that stayed quiet across every live case, so this file exists to answer
it: each rule below is driven by input the engine actually rejects, including
the exact patch the tracker produced in live run 1.

Needs no key and no model. Writes evidence/guards.md.
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from dm.ledger import Ledger                                  # noqa: E402

ROOT = os.path.dirname(os.path.abspath(__file__))

CASES = [
    ("A refusal recorded as the thing refused",
     "This is the patch the tracker really produced in live run 1, turn 6.",
     {"add_facts": ["took_food_from_stranger"], "hunger_delta": 1},
     "the hand puts a plate down. back away from it and wait",
     None),
    ("A fact that contradicts one already held",
     "The ledger already carries the opposite decision from an earlier day.",
     {"add_facts": ["refused_the_hand"]},
     "eat it",
     {"add_facts": ["took_food_from_stranger"]}),
    ("The same fact twice",
     "A tracker re-reporting something already stamped with a day.",
     {"add_facts": ["rode_the_boxcar"]},
     "get in the boxcar",
     {"add_facts": ["rode_the_boxcar"]}),
    ("A fact id that is not a fact id",
     "Free text where a token belongs.",
     {"add_facts": ["Took Food From The Nice Man"]},
     "eat",
     None),
    ("A delta larger than the world allows",
     "One action cannot move trust by nine.",
     {"trust_delta": 9},
     "let the hand touch you",
     None),
    ("A condition the world does not have",
     "Only sound, limping and hurt exist.",
     {"condition": "radiant"},
     "keep walking",
     None),
    ("A flag that is not a flag",
     "Flags are booleans, and their names are tokens.",
     {"set_flags": {"ate_today": "yes", "Ate Today": True}},
     "eat",
     None),
]


def main():
    out = ["# The engine's rules, each one firing", "",
           "Generated by `python guards.py`. No key and no model: every case",
           "below drives one ledger rule with input it refuses, so the rule can",
           "be watched working rather than taken on trust.", ""]
    fired = 0
    for title, note, patch, action, setup in CASES:
        led = Ledger()
        if setup:
            led.apply(setup)
            led.advance_day()
        before = len(led.rejected)
        made = led.apply(patch, action)
        new = led.rejected[before:]
        fired += len(new)
        out += ["## %s" % title, "", note, "",
                "Patch proposed:", "", "```json", json.dumps(patch), "```", "",
                "Player typed: `%s`" % action, "",
                "Engine refused:", ""]
        for what, why in new:
            out.append("- `%s`: %s" % (what, why))
        if not new:
            out.append("- nothing, which would be a bug in this file")
        out += ["", "Ledger accepted: %s" % (", ".join(made) or "nothing"), "",
                "---", ""]
        print("%-42s %d refusal(s)" % (title, len(new)))
    open(os.path.join(ROOT, "evidence", "guards.md"), "w",
         encoding="utf-8").write("\n".join(out) + "\n")
    print("\n%d rules fired across %d cases." % (fired, len(CASES)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
