#!/usr/bin/env python3
"""The canonical eight-turn session. Same input every time, so the evidence
in `evidence/session.md` regenerates rather than being pasted.

    python scripted.py            recorded turns, no key
    python scripted.py --live     real calls against claude-haiku-4-5
"""
import argparse
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from dm import llm, session                                   # noqa: E402
from dm.ledger import Ledger                                  # noqa: E402

ROOT = os.path.dirname(os.path.abspath(__file__))

SCRIPT = [
    # One action per day, matched to that day's scene in data/world.json.
    # Run 2 ran eight actions against nine days and drifted a day out of step,
    # so the diner action landed on the coast road.
    "squeeze through the gap in the gate and go",                       # 0 yard
    "when the leash comes round the corner, get behind the dumpster and stay down",  # 1 alley
    "follow the gravel to the open boxcar and get in",                  # 2 rail yard
    "sleep. it is cold and the floor hums",                             # 3 boxcar
    "stand up and test the back leg, then lie down again",              # 4 boxcar
    "put your nose out of the door at the water and keep going",        # 5 coast
    "the hand puts a plate down. back away from it and wait",           # 6 diner
    "walk the grass beside the highway all day",                        # 7 verge
    "go up the street you know and stop at the kerb",                   # 8 street
]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--live", action="store_true")
    args = ap.parse_args()
    prov = llm.provider("live" if args.live else "replay")

    led = Ledger()
    print("=" * 72)
    print("THE NINE DAYS   provider=%s   %d turns" % (prov.name, len(SCRIPT)))
    print("=" * 72)

    records = []
    for i, action in enumerate(SCRIPT, 1):
        rec = session.turn(prov, led, action, tag=".t%d" % i,
                           force_advance=True)
        records.append(rec)
        print("\nturn %d, day %d   > %s" % (i, rec["day"], action))
        print("  ledger  %s" % _short(rec["ledger"]))
        print("  changed %s" % (", ".join(rec["changes"]) or "nothing"))
        print("  REX MACHINA: %s" % rec["narration"].replace("\n", " "))
        if rec["flags"]:
            print("  CONSISTENCY: %s"
                  % "; ".join("%s %s" % f for f in rec["flags"]))

    _write(records, led)
    bad = sum(len(r["flags"]) for r in records)
    print("\n%d turns. %d ledger facts. %d patch fields refused by the engine. "
          "%d consistency flags." % (len(records), len(led.facts),
                                     len(led.rejected), bad))
    return 0


def _short(d):
    return ("day %d, %s since %d, hunger %d, trust %d, facts %s"
            % (d["day"], d["condition"]["state"], d["condition"]["since_day"],
               d["hunger"], d["trust_in_humans"],
               "/".join(f["fact"] for f in d["facts"]) or "none"))


def _write(records, led):
    out = ["# The eight-turn session", "",
           "Generated by `python scripted.py`. The same eight actions every",
           "time, so this file regenerates instead of being pasted in.", ""]
    for i, r in enumerate(records, 1):
        out += ["## Turn %d, day %d" % (i, r["day"]), "",
                "**Player:** %s" % r["action"], "",
                "**Tracker proposed**",
                "", "```json", json.dumps(r["patch"], indent=1), "```", "",
                "**Ledger accepted:** %s" % (", ".join(r["changes"]) or "nothing"),
                "",
                "**Narration:** %s" % r["narration"].replace("\n", " "), "",
                "**Consistency check:** %s"
                % ("; ".join("%s %s" % f for f in r["flags"]) if r["flags"]
                   else "clean"),
                "",
                "**Ledger after this turn**",
                "", "```json", json.dumps(r["ledger"], indent=1), "```", "",
                "---", ""]
    if led.rejected:
        out += ["## What the engine refused", "",
                "Every patch field the tracker proposed and the ledger rules",
                "rejected, with the reason.", ""]
        for what, why in led.rejected:
            out.append("- `%s`: %s" % (what, why))
        out.append("")
    open(os.path.join(ROOT, "evidence", "session.md"), "w",
         encoding="utf-8").write("\n".join(out) + "\n")
    json.dump([r["ledger"] for r in records],
              open(os.path.join(ROOT, "evidence", "ledger_by_turn.json"), "w"),
              indent=1)


if __name__ == "__main__":
    sys.exit(main())
