"""Generate Unreal Blueprint node text, to be pasted into a graph.

UE serialises selected Blueprint nodes to the clipboard as text and rebuilds
them on paste, wires included. So a graph can be generated and version
controlled instead of hand-wired. Every template below was captured by copying
a real node out of UE 5.5, not written from memory.

Two things that are easy to get wrong and are load-bearing here:

  * Under large world coordinates a Blueprint "float" is a double, and
    serialises as PinCategory="real" with PinSubCategory="double". Emit
    "float" and the pin silently mismatches.
  * MemberParent quoting is exact:
    MemberParent="/Script/CoreUObject.Class'/Script/Engine.KismetMathLibrary'"

Usage:
    python tools/bp_gen.py manhattan > out.txt
then paste the contents into the Manhattan graph in BP_FightManager.
"""
import sys

MATH = "/Script/CoreUObject.Class'/Script/Engine.KismetMathLibrary'"

# Pin type fragments, verbatim from captured nodes.
T_DOUBLE = 'PinType.PinCategory="real",PinType.PinSubCategory="double",PinType.PinSubCategoryObject=None'
T_INT = 'PinType.PinCategory="int",PinType.PinSubCategory="",PinType.PinSubCategoryObject=None'
T_V2D = ('PinType.PinCategory="struct",PinType.PinSubCategory="",'
         'PinType.PinSubCategoryObject="/Script/CoreUObject.ScriptStruct\'/Script/CoreUObject.Vector2D\'"')

TAIL = ('PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,'
        'PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,'
        'PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False')

FLAGS = ('PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,'
         'bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,')


def guid(seed):
    """Deterministic 32-hex GUID, so regenerating gives a byte-identical file."""
    h = 0xcbf29ce484222325
    for ch in seed.encode():
        h = ((h ^ ch) * 0x100000001b3) & 0xFFFFFFFFFFFFFFFF
    return ("%016X" % h) + ("%016X" % (h ^ 0xA5A5A5A5A5A5A5A5))


class Node:
    def __init__(self, name, member, x, y):
        self.name, self.member, self.x, self.y = name, member, x, y
        self.pins = []   # (pinname, direction, typefrag, default, links)

    def pin(self, pinname, direction, typefrag, default=None, links=()):
        self.pins.append((pinname, direction, typefrag, default, links))
        return self

    def pid(self, pinname):
        return guid(self.name + "::" + pinname)

    def render(self):
        out = [
            'Begin Object Class=/Script/BlueprintGraph.K2Node_CallFunction Name="%s"' % self.name,
            '   bDefaultsToPureFunc=True',
            '   FunctionReference=(MemberParent="%s",MemberName="%s")' % (MATH, self.member),
            '   NodePosX=%d' % self.x,
            '   NodePosY=%d' % self.y,
            '   NodeGuid=%s' % guid(self.name),
            # the hidden static-library target pin every KismetMathLibrary call carries
            '   CustomProperties Pin (PinId=%s,PinName="self",'
            'PinFriendlyName=NSLOCTEXT("K2Node", "Target", "Target"),PinType.PinCategory="object",'
            'PinType.PinSubCategory="",PinType.PinSubCategoryObject="%s",%s,'
            'DefaultObject="/Script/Engine.Default__KismetMathLibrary",'
            'PersistentGuid=00000000000000000000000000000000,bHidden=True,bNotConnectable=False,'
            'bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,'
            'bOrphanedPin=False,)' % (self.pid("self"), MATH, TAIL),
        ]
        for pinname, direction, typefrag, default, links in self.pins:
            bits = ['PinId=%s' % self.pid(pinname), 'PinName="%s"' % pinname]
            if direction == "out":
                bits.append('Direction="EGPD_Output"')
            bits.append(typefrag)
            bits.append(TAIL)
            if default is not None:
                bits.append('DefaultValue="%s"' % default)
                bits.append('AutogeneratedDefaultValue="%s"' % default)
            if links:
                bits.append('LinkedTo=(%s)' % "".join("%s %s," % (n, p) for n, p in links))
            bits.append(FLAGS)
            out.append('   CustomProperties Pin (%s)' % ",".join(bits))
        out.append('End Object')
        return "\n".join(out)


def manhattan():
    """abs(A.X - B.X) + abs(A.Y - B.Y), truncated to int.

    Boundary wires to the function entry and result nodes use the ids UE
    already assigned them in this graph, so the paste stitches itself into
    the existing entry/result rather than duplicating them.
    """
    ENTRY = "K2Node_FunctionEntry_0"
    ENTRY_A = "105817254C69A61E175EC5AD33102068"
    ENTRY_B = "4BFC60F34FF725D2F06C3EA92DB3D9E2"
    RESULT = "K2Node_FunctionResult_0"
    RESULT_D = "6F6EBA714496EB34749F14A344FCA281"

    ba = Node("RM_BreakA", "BreakVector2D", -700, -300)
    bb = Node("RM_BreakB", "BreakVector2D", -700, -80)
    sx = Node("RM_SubX", "Subtract_DoubleDouble", -450, -300)
    sy = Node("RM_SubY", "Subtract_DoubleDouble", -450, -100)
    ax = Node("RM_AbsX", "Abs", -250, -300)
    ay = Node("RM_AbsY", "Abs", -250, -100)
    ad = Node("RM_Add", "Add_DoubleDouble", -60, -200)
    tr = Node("RM_Trunc", "FTrunc", 140, -200)

    ba.pin("InVec", "in", T_V2D, links=[(ENTRY, ENTRY_A)])
    ba.pin("X", "out", T_DOUBLE, "0.0", [(sx.name, sx.pid("A"))])
    ba.pin("Y", "out", T_DOUBLE, "0.0", [(sy.name, sy.pid("A"))])

    bb.pin("InVec", "in", T_V2D, links=[(ENTRY, ENTRY_B)])
    bb.pin("X", "out", T_DOUBLE, "0.0", [(sx.name, sx.pid("B"))])
    bb.pin("Y", "out", T_DOUBLE, "0.0", [(sy.name, sy.pid("B"))])

    sx.pin("A", "in", T_DOUBLE, "0.0", [(ba.name, ba.pid("X"))])
    sx.pin("B", "in", T_DOUBLE, "0.0", [(bb.name, bb.pid("X"))])
    sx.pin("ReturnValue", "out", T_DOUBLE, "0.0", [(ax.name, ax.pid("A"))])

    sy.pin("A", "in", T_DOUBLE, "0.0", [(ba.name, ba.pid("Y"))])
    sy.pin("B", "in", T_DOUBLE, "0.0", [(bb.name, bb.pid("Y"))])
    sy.pin("ReturnValue", "out", T_DOUBLE, "0.0", [(ay.name, ay.pid("A"))])

    ax.pin("A", "in", T_DOUBLE, "0.0", [(sx.name, sx.pid("ReturnValue"))])
    ax.pin("ReturnValue", "out", T_DOUBLE, "0.0", [(ad.name, ad.pid("A"))])

    ay.pin("A", "in", T_DOUBLE, "0.0", [(sy.name, sy.pid("ReturnValue"))])
    ay.pin("ReturnValue", "out", T_DOUBLE, "0.0", [(ad.name, ad.pid("B"))])

    ad.pin("A", "in", T_DOUBLE, "0.0", [(ax.name, ax.pid("ReturnValue"))])
    ad.pin("B", "in", T_DOUBLE, "0.0", [(ay.name, ay.pid("ReturnValue"))])
    ad.pin("ReturnValue", "out", T_DOUBLE, "0.0", [(tr.name, tr.pid("A"))])

    tr.pin("A", "in", T_DOUBLE, "0.0", [(ad.name, ad.pid("ReturnValue"))])
    tr.pin("ReturnValue", "out", T_INT, "0", [(RESULT, RESULT_D)])

    return [ba, bb, sx, sy, ax, ay, ad, tr]


GRAPHS = {"manhattan": manhattan}

if __name__ == "__main__":
    which = sys.argv[1] if len(sys.argv) > 1 else "manhattan"
    if which not in GRAPHS:
        raise SystemExit("unknown graph %r; have: %s" % (which, ", ".join(sorted(GRAPHS))))
    sys.stdout.write("\n".join(n.render() for n in GRAPHS[which]()) + "\n")
