"""Check generated Blueprint node text before it is ever pasted.

    python tools/bp_lint.py generated/steptoward.txt

A pasted graph that is wrong does not announce itself: UE drops links it cannot
resolve, compiles clean, and the function quietly returns a constant. That is
exactly how `InBounds` shipped a double paste and then a missing exec wire, and
both cost an editor round trip to find. Everything checkable without UE is
checked here instead, in about a second:

  * every `LinkedTo` names a node that exists in this file, and a pin on it
  * pin ids are unique, and no node id collides
  * directions agree: an output only ever links to inputs, and vice versa
  * a non-zero `DefaultValue` never equals `AutogeneratedDefaultValue`, which
    is the trap that reverted every Band threshold to zero
  * pin types match across a link, so a double never lands on an int pin

One-sided links are reported as notes, not failures. UE writes both ends of a
wire, but it repairs a link declared on only one end when it pastes: the
shipped `inbounds.txt` and `selftest.txt` both declare several one-sided and
both produce correct graphs. Worth emitting symmetrically anyway, so the text
matches what UE writes back and a round trip through the editor diffs cleanly.

Exit code is 1 only for real failures, so it can gate a regeneration.
"""
import re
import sys
import collections

NODE_RE = re.compile(r'Begin Object Class=(\S+) Name="([^"]+)"')
PIN_RE = re.compile(r'CustomProperties Pin \((.*)\)\s*$')


def parse(text):
    """-> [(node_name, class, [pin dicts])], in file order."""
    nodes, cur = [], None
    for line in text.splitlines():
        m = NODE_RE.search(line)
        if m:
            cur = {"name": m.group(2), "class": m.group(1).rsplit(".", 1)[-1], "pins": []}
            nodes.append(cur)
            continue
        m = PIN_RE.search(line.strip())
        if m and cur is not None:
            body = m.group(1)
            pin = {
                "id": _field(body, "PinId"),
                "name": _field(body, 'PinName', quoted=True),
                "dir": "out" if 'Direction="EGPD_Output"' in body else "in",
                "cat": _field(body, "PinType.PinCategory", quoted=True),
                "sub": _field(body, "PinType.PinSubCategory", quoted=True),
                "obj": _field(body, "PinType.PinSubCategoryObject", quoted=True),
                "default": _field(body, "DefaultValue", quoted=True),
                "autogen": _field(body, "AutogeneratedDefaultValue", quoted=True),
                "links": _links(body),
            }
            cur["pins"].append(pin)
    return nodes


def _field(body, key, quoted=False):
    pat = (r'(?<![\w.])' + re.escape(key) + r'="([^"]*)"') if quoted \
        else (r'(?<![\w.])' + re.escape(key) + r'=([0-9A-Fa-f]+)')
    m = re.search(pat, body)
    return m.group(1) if m else None


def _links(body):
    m = re.search(r'LinkedTo=\(([^)]*)\)', body)
    if not m:
        return []
    out = []
    for part in m.group(1).split(","):
        part = part.strip()
        if not part:
            continue
        node, _, pid = part.rpartition(" ")
        out.append((node, pid))
    return out


def lint(nodes):
    problems, notes = [], []

    def bad(fmt, *a):
        problems.append(fmt % a)

    def note(fmt, *a):
        notes.append(fmt % a)

    by_name = {}
    for n in nodes:
        if n["name"] in by_name:
            bad("duplicate node name %s", n["name"])
        by_name[n["name"]] = n

    pin_of = {}                       # pin id -> (node, pin)
    seen_ids = collections.Counter()
    for n in nodes:
        for p in n["pins"]:
            seen_ids[p["id"]] += 1
            pin_of[p["id"]] = (n, p)
    for pid, count in seen_ids.items():
        if count > 1:
            bad("pin id %s used %d times -- the guid seed collided", pid, count)

    for n in nodes:
        for p in n["pins"]:
            # Only a non-zero literal is at risk: if the two match and the
            # value is the type's own zero, UE rewriting the pin from the
            # signature puts back the same number. A non-zero literal that
            # matches is the Band bug, and reverts to zero on paste.
            if (p["default"] is not None and p["default"] == p["autogen"]
                    and p["default"] not in ("", "0", "0.0", "false", "None")):
                bad("%s.%s: DefaultValue == AutogeneratedDefaultValue (%r); "
                    "UE will treat the pin as unedited and revert it to zero",
                    n["name"], p["name"], p["default"])
            for tgt_node, tgt_pid in p["links"]:
                if tgt_node not in by_name:
                    bad("%s.%s links to unknown node %s", n["name"], p["name"], tgt_node)
                    continue
                if tgt_pid not in pin_of:
                    bad("%s.%s links to unknown pin id %s on %s",
                        n["name"], p["name"], tgt_pid, tgt_node)
                    continue
                on, op = pin_of[tgt_pid]
                if on["name"] != tgt_node:
                    bad("%s.%s links to %s %s but that pin belongs to %s",
                        n["name"], p["name"], tgt_node, tgt_pid, on["name"])
                    continue
                if (n["name"], p["id"]) not in [(a, b) for a, b in op["links"]]:
                    note("one-sided: %s.%s -> %s.%s, not declared back "
                         "(UE repairs this on paste)",
                         n["name"], p["name"], on["name"], op["name"])
                if p["dir"] == op["dir"]:
                    bad("%s.%s and %s.%s are both %sputs",
                        n["name"], p["name"], on["name"], op["name"], p["dir"])
                if (p["cat"], p["sub"], p["obj"]) != (op["cat"], op["sub"], op["obj"]):
                    bad("type mismatch %s.%s (%s/%s) -> %s.%s (%s/%s)",
                        n["name"], p["name"], p["cat"], p["sub"],
                        on["name"], op["name"], op["cat"], op["sub"])
    return problems, notes


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        return 2
    rc = 0
    for path in [a for a in sys.argv[1:] if not a.startswith("-")]:
        with open(path, encoding="utf-8") as fh:
            nodes = parse(fh.read())
        problems, notes = lint(nodes)
        pins = sum(len(n["pins"]) for n in nodes)
        wires = sum(len(p["links"]) for n in nodes for p in n["pins"]) // 2
        print("%s: %d nodes, %d pins, %d wires" % (path, len(nodes), pins, wires))
        for p in sorted(set(problems)):
            print("  ! " + p)
        if notes and "-v" in sys.argv:
            for p in sorted(set(notes)):
                print("  . " + p)
        if problems:
            print("  %d problem(s)" % len(set(problems)))
            rc = 1
        else:
            print("  clean" + (", %d note(s)" % len(set(notes)) if notes else ""))
    return rc


if __name__ == "__main__":
    sys.exit(main())
