"""Create BP_SelfTest, a child of BP_FightManager that asserts its own maths.

    exec(open(r"D:/Side Projects/AI Game Dev Course/rex-machina/tools/ue_make_selftest.py").read())

A Blueprint graph cannot be read back and checked -- there is no K2Node API --
so "it compiled" is the only structural signal, and a Blueprint compiles happily
with a wire on the wrong pin. Band proved that: it pasted once with every
threshold at 0.0 and every string empty, and compiled clean.

The answer is to check behaviour instead of structure. Parenting the test to
BP_FightManager means Manhattan, Band and the rest are inherited and callable on
self, so no actor references need wiring.

This script only creates the asset. The assertion graph is generated by
tools/bp_gen.py and pasted in.
"""
import unreal

BEL = unreal.BlueprintEditorLibrary
L = unreal.log
E = unreal.log_error

PKG = "/Game/Blueprints"
NAME = "BP_SelfTest"
PATH = "%s/%s" % (PKG, NAME)
PARENT_PATH = "/Game/Blueprints/BP_FightManager.BP_FightManager"


def main():
    parent_bp = unreal.load_asset(PARENT_PATH)
    if parent_bp is None:
        E("BP_FightManager not found at %s" % PARENT_PATH)
        return

    parent_class = parent_bp.generated_class()
    if parent_class is None:
        E("BP_FightManager has no generated class -- compile it first")
        return

    bp = unreal.load_asset(PATH + "." + NAME)
    if bp is None:
        factory = unreal.BlueprintFactory()
        factory.set_editor_property("parent_class", parent_class)
        bp = unreal.AssetToolsHelpers.get_asset_tools().create_asset(
            NAME, PKG, unreal.Blueprint, factory)
    if bp is None:
        E("could not create %s" % PATH)
        return

    BEL.compile_blueprint(bp)
    unreal.EditorAssetLibrary.save_asset(PATH)

    L("---- BP_SelfTest ----")
    L("  created %s" % PATH)
    L("  parent  %s" % parent_class.get_name())
    L("  inherited functions are callable on self; paste the assertion graph")
    L("  into its EventGraph next.")


main()
